name: CTran

method: NLL

resume_model: /root/autodl-tmp/mlp-pl/exp/checkpoint/2023-10-21-CTran-COCO2014-DPCAR-eps0_05/checkpoint_best.pth
aux_model: /root/autodl-tmp/mlp-pl/exp/checkpoint/2023-10-19-SSGRL-COCO2014-DPCAR-eps0_05/checkpoint_best.pth

# instance inter loss setting
inter_BCE_weight: 1.0
inter_BCE_margin: 0.95
inter_distance_weight: 0.05
inter_example_nums: 100

# prototype inter loss setting
inter_prototype_distance_weight: 0.05
prototype_nums: 10
use_recompute_prototype: true    # whether to recompute prototype
compute_prototype_epoch: 5    # when to generate pseudo label

# label smoothing setting
eps: 0.05
generate_label_epoch: 5