name: SSGRL

method: LS

# NLL
# resume_model: /root/autodl-tmp/mlp-pl/exp/checkpoint/2023-11-02-SSGRL-COCO2014-NLL-eps0_05/checkpoint_best.pth

# LS
resume_model: /root/autodl-tmp/mlp-pl/exp/checkpoint/2023-11-03-SSGRL-COCO2014-label_smoothing-eps0_05/checkpoint_best.pth

# DPCAR
# resume_model: /root/autodl-tmp/mlp-pl/exp/checkpoint/2023-10-19-SSGRL-COCO2014-DPCAR-eps0_05/checkpoint_best.pth

aux_model: None

# instance inter loss setting
inter_BCE_weight: 1.0
inter_BCE_margin: 0.95
inter_distance_weight: 0.05
inter_example_nums: 100

# prototype inter loss setting
inter_prototype_distance_weight: 0.05
prototype_nums: 10
use_recompute_prototype: true    # whether to recompute prototype
compute_prototype_epoch: 5    # when to generate pseudo label

# label smoothing setting
eps: 0.05
generate_label_epoch: 5
