name: MLGCN

method: NLL

resume_model: None
teacher_model: None

# instance inter loss setting
inter_BCE_weight: 1.0
inter_BCE_margin: 0.95
inter_distance_weight: 0.05
inter_example_nums: 100

# prototype inter loss setting
inter_prototype_distance_weight: 0.05
prototype_nums: 10
use_recompute_prototype: true    # whether to recompute prototype
compute_prototype_epoch: 5    # when to generate pseudo label

# label smoothing setting
eps: 0.05
generate_label_epoch: 5

lrp: 0.1
max_clip_grad_norm: 10