defaults:
  - dataset: COCO
  - model: SSGRL

save_path: /root/autodl-tmp/mlp-pl/exp/checkpoint
resume_model: None
aux_model: None

pretrained_model: /root/autodl-tmp/data/checkpoint/resnet101.pth

epochs: 20
start_epoch: 0
step_epoch: 15
evaluate: true
seed: 1407

batch_size: 1
print_freq: 800

lr: 1e-05
momentum: 0.9
weight_decay: 0

crop_size: 448
scale_size: 512
workers: 8

# will be automatically populated at runtime
post: ???