name: 'VG'
class_nums: 200

data_dir: /root/autodl-tmp/vg/vg
# data_category_map: ''
data_vector: /root/autodl-tmp/data/vg/vg_200_vector.npy

train_image_list: /root/autodl-tmp/data/vg/train_list_500.txt
test_image_list: /root/autodl-tmp/data/vg/test_list_500.txt
train_label: /root/autodl-tmp/data/vg/vg_category_200_labels_index.json
test_label: /root/autodl-tmp/data/vg/vg_category_200_labels_index.json

prob: 1.0

